source "https://rubygems.org/"
ruby "2.1.2"
gem 'sinatra', '1.4.5' 
gem 'tilt', '1.4.1'
gem 'rack', '1.5.2'
gem 'rack-protection', '1.5.0'
gem 'rspec', '3.0.0'
gem 'rspec-core', '3.0.1'
gem 'math24', '1.1.2'
gem 'require_all'
gem 'thin'
gem 'shotgun'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3'